body:
- attributes:
    value: Thanks for taking the time to add a new project
  type: markdown
- attributes:
    description: The name of the project
    label: Name
    placeholder: ex. Polkadot SDK
  id: name
  type: input
  validations:
    required: true
- attributes:
    description: What interests are related to the project?
    label: Interests
    multiple: true
    options:
    - polkadot
    - kusama
    - substrate
    - evm
    - defi
    - smart contracts
    - ink!
    - bridge
    - dex
    - dao
    - social
    - zero-knowledge
    - iot
    - xcm
    - wallet
    - ai
    - dapp
    - data
    - oracles
    - gaming
    - nft
    - staking
    - utilities
    - rwa
    - docs
    - marketplace
  id: interests
  type: dropdown
  validations:
    required: true
- attributes:
    description: The URL of the project
    label: Repository URL
    placeholder: ex. https://github.com/paritytech/polkadot-sdk
  id: url
  type: input
  validations:
    required: true
description: Add a new project
labels:
- new-project
name: New Project
title: '[Add]: '
