name: Register repository and load issues

on:
  workflow_dispatch:
    inputs:
      projectName:
        description: "The project name that will be visible on Kudos"
        required: true
      repoUrl:
        description: "The repository URL from which to import the issues"
        required: true

jobs:
  run-import-action:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: |
          echo ${{ github.event.inputs.projectName }}
          echo ${{ github.event.inputs.repoUrl }}

      - name: Run Custom Import Issues Action
        id: import_issues
        uses: kudos-ink/import-issues@v0.0.1
        with:
          project-name: ${{ github.event.inputs.projectName }}
          repo-url: ${{ github.event.inputs.repoUrl }}
          issues-db-id: ${{ vars.ISSUES_DB_ID }}
          repo-list-db-id: ${{ vars.REPO_LIST_DB_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          notion-api-key: ${{ secrets.NOTION_API_KEY }}

      - name: Print output
        run: |
          echo "The repository id is ${{ steps.import_issues.outputs.repository_id }}"

      - name: Error importing the issues
        if: "${{ steps.import_issues.outputs.failed_import_links != '' }}"
        run: |
          echo "There were some errors in the import action: ${{ steps.import_issues.outputs.failed_import_links }}"
          exit 1
