name: Update repositories

on:
  push:
    branches:
      - main
    paths:
      - "**/repository.json"
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute uppdater
        run: |
          python repository_parser.py
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Commit Changes
        run: |
          git config --local user.email "updater@github.com"
          git config --local user.name "Updater"

          git add .
          git commit -m "Update from GitHub Action"
          git push
